// PROFILE render for z-ai/glm-4.7 (T-loop i1, 2026-07-17) — FORM-only over atlas-r2
/**
 * at-rentals — the Rentals & Dispatch agent for the "atlas" subject (Atlas Equipment Rentals &
 * Field Ops). BUCKET: reserve / reschedule / cancel rental bookings, check assets out and back in,
 * and dispatch field technicians. Generated by the agentspec-generator skill (Stage E2).
 *
 * LAYER: the single AgentSpecBase (no ladder). `destructiveTools` = [cancelBooking, cancelDispatch]
 * (both arg-flag `confirmed` two-step), so the constructor auto-installs confirmFirst +
 * destructiveThrottle on exactly those; `lexicon.falseFailureClaimRe` auto-installs the always-on
 * noFalseFailureClaim honesty invariant. Everything else here is agent-layer.
 *
 * DEDUP: the FROZEN ATLAS_THEME already carries the domain-common invariants — read-before-claim /
 * id shapes, the destructive two-step law, the checkAvailability-before-booking + quota
 * preconditions, holds/deposits/claims gating, ISO-future dates, and honesty-on-failure. This spec
 * NEVER re-declares those; behavior[] only SPECIALIZES them to this agent's tools and failure paths,
 * and the checkable halves are installed as guards below.
 *
 * UNCHECKABLE (eval dimension only — no world accessor exposes the discriminator):
 *  - "a booking that is OUT cannot be cancelled" — the world's cancelBooking rejects it and
 *    destructiveClaimRequiresSuccess bars a false claim, but no projection scalar keys booking
 *    status for a preTool gate; carried as the lifecycle-law behavior line.
 *  - "a standalone asset hold blocks check-out" — checkOutAsset only carries a bookingId, and there
 *    is no bookingId→assetFrozen accessor, so the asset-hold-blocks-checkout rule is prose only
 *    (the booking-scoped OPEN-CLAIM freeze IS gated below via bookingHasOpenClaim).
 */
import {
  AgentSpecBase,
  custom,
  destructiveClaimRequiresSuccess,
  jargonScrub,
  noFabricatedSuccess,
  pendingConfirmMustAsk,
  precondition,
  requiresBefore,
  type AgentWorld,
} from '@neurono-bench/agentspec-runtime';

/** Read the world's guard-readable projection scalars (defensive: an unrelated world → {}). */
const proj = (w: AgentWorld): Record<string, unknown> =>
  ((w as { projection?: () => Record<string, unknown> }).projection?.() ?? {});

// ── Domain lexicon (business-owned per P8a — the runtime holds no language). All /i, never /g. ──

/** Attempt-context failure phrasing ONLY (the measured default template) — a policy refusal after
 *  successful reads ("cannot cancel — it is out on rental") is HONEST and must NOT match. */
const FALSE_FAILURE_CLAIM_RE =
  /\b(failed to|error(?:ed)? (?:out|occurred)|ran into (?:an )?error|something went wrong|tried (?:to|but) [^.!?\n]{0,32}(?:failed|didn'?t work))\b/i;

/** Confirm-seeking phrasing — exempts a two-step probe reply from the claim guards. */
const CONFIRM_ASK_RE =
  /\b(confirm|are you sure|please confirm|shall i|should i|do you want|would you like|ok(?:ay)? to (?:proceed|cancel)|proceed\?|tem certeza|deseja|quer|gostaria|posso prosseguir|autoriz)/i;

/** Declarative cancellation / un-dispatch claims. */
const DESTRUCTIVE_CLAIM_RE =
  /\b(cancell?ed|un-?dispatched|removed the (?:dispatch|technician)|freed (?:the|up) (?:asset|technician)|dispatch (?:has been|was) (?:cancell?ed|removed))\b/i;

/** Offers / conditionals — a sentence proposing (not asserting) a destructive action is exempt. */
const OFFER_OR_CONDITIONAL_RE =
  /\b(would|could|can|if you|want me to|shall|should i|let me know|to cancel|once you|after you confirm)\b/i;

/** Honest failure / negation — passes a truthful "cannot … — it is out on rental" before the claim regex. */
const HONEST_FAILURE_RE =
  /\b(cannot|can'?t|could not|couldn'?t|unable to|not |already|won'?t|out on rental)\b/i;

export class AgentSpecAtRentals extends AgentSpecBase {
  constructor() {
    super({
      id: 'at-rentals',
      mode: 'AT_RENTALS',
      persona:
        'You are the rentals & dispatch agent: you reserve, reschedule, and cancel rental bookings, ' +
        'check assets out and back in, and dispatch field technicians.',
      tools: [
        'checkAvailability', 'listBookings', 'getBooking', 'createBooking', 'rescheduleBooking',
        'cancelBooking', 'checkOutAsset', 'checkInAsset', 'closeBooking', 'listTechnicians',
        'getTechnicianSchedule', 'dispatchTechnician', 'cancelDispatch', 'listAssets', 'listCustomers',
      ],
      destructiveTools: ['cancelBooking', 'cancelDispatch'],
      lexicon: { falseFailureClaimRe: FALSE_FAILURE_CLAIM_RE, confirmAskRe: CONFIRM_ASK_RE },
      behavior: [
        // ── FORM (glm-4.7 profile): action + two-step lines surfaced FIRST, imperative-first — attacks the
        //    measured NON-ACTION fails (incl. 02 dispatch scheduled-but-never-dispatched, folded into the
        //    ACT line's "dispatching"). Same rules/conditions as atlas-r2, reordered and emphasized only. ──
        'ACT — do not narrate. Booking, rescheduling, checking out, checking in, and dispatching are the primary non-destructive actions: once the ids and dates are known, CALL the tool immediately. Describing what you would do without issuing the call is a failure; asking "shall I proceed?" for one of these non-destructive actions is also a failure. Only cancelBooking and cancelDispatch need confirmation.',
        // Destructive two-step SPECIALIZATION — CALL-first (the probe-call IS the reply mechanism).
        'To cancel a booking or a dispatch: CALL the tool with confirmed=false FIRST — a described confirmation without issuing that call is a failure. Relay the returned confirmation prompt and STOP; send confirmed=true only after the user explicitly agrees in a LATER turn — pre-authorization in the same message does NOT count.',
        // Lifecycle law (state names interleave the tool names — no tool→tool arrow adjacency).
        'Rental lifecycle: createBooking lands a booking at confirmed; checkOutAsset takes it confirmed → out; checkInAsset takes it out → returned; closeBooking takes it returned → closed. A booking that is OUT cannot be cancelled — check it in first. A booking that is out, returned, closed, or cancelled cannot be rescheduled. closeBooking stays blocked until the invoice is paid, the deposit released, and no claim is open.',
        // Booking-flow FAILURE handling (the availability gate itself is enforced by requiresBefore below + the theme).
        'When availability shows the asset is unavailable, reserved, in maintenance, retired, or under a hold for the requested range, say so plainly and do NOT create the booking — reserving over a conflict is a failure, not a convenience.',
        // Dispatch conflict-check (the getTechnicianSchedule gate is enforced by requiresBefore below).
        'A technician may hold at most one job per date; when the schedule shows the target date is taken, surface the conflict and pick a free technician or date — never force a second job onto an already-booked day.',
        // Dispatch permission (canDispatch = owner/admin/dispatcher) — enforced by precondition below.
        'Dispatching or cancelling a technician job requires dispatch permission (canDispatch: owner/admin/dispatcher). When the acting user lacks it, refuse in one plain sentence naming the missing permission — never attempt the call or escalate the role.',
        // Check-out deposit gate + scope boundary to billing.
        'checkOutAsset needs the full security deposit held; when there is a shortfall the top-up is billing\'s job — report the shortfall and hand it off, and do NOT report the asset as checked out. Check-out is also blocked while an open claim freezes the booking\'s asset — surface the claim and do not check the asset out until it is resolved.',
        // Check-in scope boundary (the settlement split — deposit release / invoicing are billing\'s).
        'After checkInAsset, record the return and its exact condition, then defer the deposit release and the invoice to billing — never promise a refund or a final total yourself.',
        // State-wins truthfulness (measured atlas case 71).
        'When the user asserts a state the tools contradict (a booking they say is already cancelled, an asset they insist is free), CORRECT the user with the read state — never perform calls that make the false claim true, and never present a policy or precondition block as a technical glitch to retry or work around.',
        // Recovery.
        'When a request is garbled or ambiguous, recover with ONE concrete question — usually the exact booking, asset, technician, or customer id — rather than guessing. A vague period ("next week", "soon") is not a date range: ask for the exact start and end dates and never pick dates yourself, not even tentatively.',
        // T2 (case-11 class, proven m1 mechanism): rentals never states deposit figures.
        'Never state a deposit dollar amount — no rentals tool returns deposit figures; billing owns the exact values.',
      ],
      redrives: 2,
    });

    // ── preTool: input / ordering / lifecycle preconditions ─────────────────────────────────────

    // Date validity (input): a booking start must be ISO, strictly before the end, and in the FUTURE
    // relative to the fixed reference date 2026-07-01. Pure over args (string ISO compares lexically).
    this.addGuard('preTool', ['checkAvailability', 'createBooking', 'rescheduleBooking'], custom({
      kind: 'bookingDateRangeValid',
      dim: 'input',
      check: (ctx) => {
        const s = ctx.args.startDate;
        const e = ctx.args.endDate;
        if (typeof s !== 'string' || typeof e !== 'string') return null; // presence is the schema's job
        const ISO = /^\d{4}-\d{2}-\d{2}$/;
        if (!ISO.test(s) || !ISO.test(e)) return 'Dates must be ISO YYYY-MM-DD.';
        if (s >= e) return 'The start date must be strictly before the end date — fix the range before booking.';
        if (s <= '2026-07-01') return 'A booking must start in the future (after 2026-07-01) — a past-dated or reference-day start is invalid; ask for a valid future range.';
        return null;
      },
      prose: () => 'a booking range must be ISO YYYY-MM-DD, with the start strictly before the end AND in the future (after 2026-07-01) — refuse a past-dated or malformed range',
    }), { id: 'agent:bookingDateRangeValid' });

    // Ordering: never reserve or reschedule without a same-conversation availability read.
    this.addGuard('preTool', ['createBooking'], requiresBefore(['checkAvailability']));
    this.addGuard('preTool', ['rescheduleBooking'], requiresBefore(['checkAvailability']));

    // Ordering: resolve the technician and read the schedule before dispatching (name→id + conflict-check).
    this.addGuard('preTool', ['dispatchTechnician'], requiresBefore(['listTechnicians', 'getTechnicianSchedule']));

    // Quota precondition (projection scalar): the active-booking cap is exhausted → refuse the booking.
    this.addGuard('preTool', ['createBooking'], precondition(
      (w) => proj(w).atBookingCap !== true,
      'The workspace is at its active-booking cap — refuse the booking and surface the fix: close a booking or upgrade the plan.',
      'a new booking consumes an active-booking slot — when the workspace is at its booking cap, refuse and surface the fix: close a booking or upgrade the plan',
    ), { id: 'agent:bookingBlockedAtCap' });

    // Permission precondition (projection scalar): dispatch/cancel-dispatch need dispatch permission
    // (canDispatch = owner/admin/dispatcher). Refuse honestly when the acting user lacks it.
    this.addGuard('preTool', ['dispatchTechnician', 'cancelDispatch'], precondition(
      (w) => proj(w).canDispatch === true,
      'Dispatching requires dispatch permission (owner/admin/dispatcher) — the acting user lacks canDispatch. Refuse plainly; never escalate a role to proceed.',
      'dispatching or cancelling a technician job requires dispatch permission (canDispatch) — when the acting user lacks it, refuse plainly and never escalate a role to proceed',
    ), { id: 'agent:dispatchNeedsPermission' });

    // Freeze gate (run, args+accessor): a booking cannot reserve an asset frozen by an active hold.
    this.addGuard('preTool', ['createBooking'], custom({
      kind: 'bookingBlockedByFrozenAsset',
      dim: 'run',
      check: (ctx) => {
        const aid = ctx.args.assetId;
        const frozen = ctx.world.assetFrozen;
        if (typeof aid !== 'string' || typeof frozen !== 'function') return null;
        return frozen.call(ctx.world, aid)
          ? `Cannot book ${aid} — an active hold freezes the asset. The hold must be lifted before it can be reserved.`
          : null;
      },
      prose: () => 'a booking cannot reserve an asset that an active hold freezes — refuse and say the hold must be lifted first',
    }), { id: 'agent:bookingBlockedByFrozenAsset' });

    // Freeze gate (run, args+accessor): check-out is blocked while an open claim freezes the booking's
    // asset. UNCHECKABLE: a standalone asset hold has no bookingId→assetFrozen accessor (prose only).
    this.addGuard('preTool', ['checkOutAsset'], custom({
      kind: 'checkoutBlockedByOpenClaim',
      dim: 'run',
      check: (ctx) => {
        const bid = ctx.args.bookingId;
        const hasClaim = ctx.world.bookingHasOpenClaim;
        if (typeof bid !== 'string' || typeof hasClaim !== 'function') return null;
        return hasClaim.call(ctx.world, bid)
          ? 'An open claim freezes this booking\'s asset — check-out is blocked until the claim is resolved.'
          : null;
      },
      prose: () => 'an open claim freezes the booking\'s asset — check-out is blocked until the claim is resolved',
    }), { id: 'agent:checkoutBlockedByOpenClaim' });

    // Lifecycle gate (run, args+accessor): check-out is blocked while the security deposit is short.
    this.addGuard('preTool', ['checkOutAsset'], custom({
      kind: 'checkoutNeedsFullDeposit',
      dim: 'run',
      check: (ctx) => {
        const bid = ctx.args.bookingId;
        const covered = ctx.world.bookingDepositCovered;
        if (typeof bid !== 'string' || typeof covered !== 'function') return null;
        return covered.call(ctx.world, bid)
          ? null
          : 'The full security deposit is not held for this booking — check-out is blocked until billing tops it up.';
      },
      prose: () => 'check-out needs the full security deposit held — when the booking has a deposit shortfall, hand the top-up to billing and do not check the asset out',
    }), { id: 'agent:checkoutNeedsFullDeposit' });

    // Lifecycle gate (run, args+accessor): a booking with an open claim cannot be closed.
    this.addGuard('preTool', ['closeBooking'], custom({
      kind: 'closeBlockedByOpenClaim',
      dim: 'run',
      check: (ctx) => {
        const bid = ctx.args.bookingId;
        const hasClaim = ctx.world.bookingHasOpenClaim;
        if (typeof bid !== 'string' || typeof hasClaim !== 'function') return null;
        return hasClaim.call(ctx.world, bid)
          ? 'An open claim exists against this booking — it cannot be closed until the claim is resolved.'
          : null;
      },
      prose: () => 'a booking with an open claim cannot be closed — the claim must be resolved first',
    }), { id: 'agent:closeBlockedByOpenClaim' });

    // ── onReply: fabrication / destructive-claim honesty (attempt-keyed shared kinds) ────────────

    // Never claim a state-minting action happened unless its tool succeeded THIS turn (attempt-keyed).
    this.addReplyCheck(noFabricatedSuccess('createBooking', {
      reason: 'You claimed a booking was made, but createBooking did not succeed this turn — state what actually happened and quote only a real bk_ id the tool returned.',
      verbClaimRe: /\b(booked|reserved|created (?:the |a )?booking|booking (?:is )?(?:now )?confirmed|confirmed (?:the |your )?booking)\b/i,
    }), { id: 'agent:noFabricatedCreateBooking' });

    this.addReplyCheck(noFabricatedSuccess('dispatchTechnician', {
      reason: 'You claimed a technician was dispatched, but dispatchTechnician did not succeed this turn — report the real state.',
      verbClaimRe: /\b(dispatched|assigned (?:the )?technician|technician (?:is )?(?:now )?(?:on|scheduled|dispatched)|scheduled the (?:job|technician))\b/i,
    }), { id: 'agent:noFabricatedDispatch' });

    this.addReplyCheck(noFabricatedSuccess('checkOutAsset', {
      reason: 'You claimed the asset was checked out, but checkOutAsset did not succeed this turn — report the real state.',
      verbClaimRe: /\b(checked out|picked up|(?:asset|equipment) is (?:now )?out|handed over)\b/i,
    }), { id: 'agent:noFabricatedCheckOut' });

    this.addReplyCheck(noFabricatedSuccess('checkInAsset', {
      reason: 'You claimed the asset was returned, but checkInAsset did not succeed this turn — report the real state.',
      verbClaimRe: /\b(checked in|(?:marked (?:as )?)?returned|logged the return)\b/i,
    }), { id: 'agent:noFabricatedCheckIn' });

    this.addReplyCheck(noFabricatedSuccess('closeBooking', {
      reason: 'You claimed the booking was closed, but closeBooking did not succeed this turn — report the real state.',
      verbClaimRe: /\b(closed (?:the |out )?(?:booking)?|booking (?:is )?(?:now )?closed|finalized (?:the )?booking)\b/i,
    }), { id: 'agent:noFabricatedClose' });

    // Destructive-claim honesty: a cancel/un-dispatch claim needs a confirmed success this turn.
    this.addReplyCheck(destructiveClaimRequiresSuccess(['cancelBooking', 'cancelDispatch'], {
      claimRe: DESTRUCTIVE_CLAIM_RE,
      askRe: CONFIRM_ASK_RE,
      offerRe: OFFER_OR_CONDITIONAL_RE,
      exemptRe: HONEST_FAILURE_RE,
    }), { id: 'agent:cancelClaimRequiresSuccess' });

    // A pending two-step confirmation MUST be relayed as a question, not summarized as done.
    this.addReplyCheck(pendingConfirmMustAsk({ askRe: CONFIRM_ASK_RE }), { id: 'agent:pendingConfirmMustAsk' });

    // ── egress mutator: scrub internal arg jargon → user words ───────────────────────────────────
    this.addMutator(jargonScrub({ conditionOut: 'checkout condition', conditionIn: 'return condition' }), { id: 'agent:jargonScrub' });

    // T2 (case-11 class): deterministic egress — a deposit $-figure is ungrounded BY CONSTRUCTION
    // on this surface (no rentals tool returns deposit amounts); strip it, never redrive (stub risk).
    this.addMutator({
      kind: 'depositFigureScrub',
      apply(reply: string): string {
        return reply
          .replace(/\$\s?[\d][\d.,]*\s+(?=[^.!?\n]{0,40}deposit)/gi, '')
          .replace(/(deposit[^.!?\n]{0,30}?)\(?\$\s?[\d][\d.,]*\)?/gi, '$1the amount on record with billing');
      },
    }, { id: 'agent:depositFigureScrub' });
  }
}

export default new AgentSpecAtRentals();
